#!/usr/bin/env python

from subprocess import call
import os
import argparse
import shutil

# Constant definition
# ===================
PATH_LINKS = os.path.join(os.getenv("HOME"), '.mypath')

# Parsing arguments
# =================

def to_str_or_quotes(o):
          """Converts a value to string or add quotes"""
          if isinstance(o, basestring):
               return '"' + o + '"'
          else:
               return str(o)

parser = argparse.ArgumentParser(
	description="The last program you will have to manualy add to your path. You should put this program in the PATH_LINKS directory (default ~/.mypath/) and add this directory to you path in your .bash_profile" 
)
parser.add_argument(
	'to_link',
	metavar='files to link',
	nargs='+',
	type=str
)



dic = vars(parser.parse_args())
to_link = parser.parse_args().to_link
print to_link

src_to_link = [os.path.join(os.getcwd(), f ) for f in to_link] 
temp = []
for i in range(len(src_to_link)):
	if os.path.isfile(src_to_link[i]):
		# print src_to_link, os.path.join(PATH_LINKS, to_link[i])
		os.symlink(src_to_link[i], os.path.join(PATH_LINKS, to_link[i]))
		print( "The file '%s' was symbolicly linked succesfully" % src_to_link[i] )


